/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/report/validate/{validationId}": {
    put: operations["validate"];
  };
  "/admin/trail/update": {
    put: operations["updateTrail"];
  };
  "/admin/trail/save": {
    put: operations["importTrail"];
  };
  "/admin/report": {
    put: operations["update"];
    post: operations["create_5"];
  };
  "/admin/report/upgrade/{id}": {
    put: operations["upgradeReport"];
  };
  "/admin/poi": {
    put: operations["update_1"];
    post: operations["create_6"];
  };
  "/admin/place": {
    put: operations["create"];
    post: operations["update_2"];
  };
  "/admin/place/unlink/trail": {
    put: operations["unLinkTrailToPlace"];
  };
  "/admin/place/media/{id}": {
    put: operations["addMedia"];
    post: operations["deleteMedia"];
  };
  "/admin/place/link/trail": {
    put: operations["linkTrailToPlace"];
  };
  "/admin/maintenance": {
    put: operations["create_1"];
  };
  "/admin/announcement": {
    put: operations["create_2"];
    post: operations["update_3"];
  };
  "/admin/accessibility": {
    put: operations["create_3"];
  };
  "/report": {
    post: operations["create_4"];
  };
  "/place/geolocate": {
    post: operations["geolocatePlace"];
  };
  "/geo-trail/locate": {
    post: operations["geoLocateTrail"];
  };
  "/geo-trail/locate-id": {
    post: operations["geoLocateTrail_1"];
  };
  "/geo-trail/intersect": {
    post: operations["findTrailIntersection"];
  };
  "/geo-tool/distance": {
    post: operations["radialDistance"];
  };
  "/admin/trail/status": {
    post: operations["updateTrailStatus"];
  };
  "/admin/trail/place/{id}": {
    post: operations["addPlaceToTrail"];
    delete: operations["removePlaceFromTrail"];
  };
  "/admin/trail/media/{id}": {
    post: operations["addMediaToTrail"];
    delete: operations["removeMediaFromTrail"];
  };
  "/admin/trail-preview/list/export": {
    post: operations["downloadCsv"];
  };
  "/admin/resource/status": {
    post: operations["getGenerationResourceStatus"];
  };
  "/admin/resource/regenerate": {
    post: operations["generateResource"];
  };
  "/admin/resource/regenerate/all": {
    post: operations["generateResource_1"];
  };
  "/admin/poi/media/{id}": {
    post: operations["addMediaToPoi"];
    delete: operations["removeMediaFromPoi"];
  };
  "/admin/media": {
    post: operations["upload"];
  };
  "/admin/import": {
    post: operations["importGpx"];
  };
  "/admin/import/check": {
    post: operations["checkMatchingTrails"];
  };
  "/admin/import/bulk": {
    post: operations["importMassiveGpx"];
  };
  "/admin/accessibility/resolve": {
    post: operations["resolveNotification"];
  };
  "/trail": {
    get: operations["get"];
  };
  "/trail/{id}": {
    get: operations["getById"];
  };
  "/trail/place/{id}": {
    get: operations["getByPlaceId"];
  };
  "/trail/count": {
    get: operations["getCount"];
  };
  "/report/{id}": {
    get: operations["getById_1"];
  };
  "/report/upgraded/{realm}": {
    get: operations["getUpgraded"];
  };
  "/report/trail/{id}": {
    get: operations["getByTrailId"];
  };
  "/report/not-upgraded/{realm}": {
    get: operations["getUnapgraded"];
  };
  "/report/count/{realm}": {
    get: operations["getCount_1"];
  };
  "/raw": {
    get: operations["get_1"];
  };
  "/raw/{id}": {
    get: operations["getById_2"];
  };
  "/preview": {
    get: operations["getTrailPreviews"];
  };
  "/preview/{id}": {
    get: operations["getPreviewById"];
  };
  "/preview/raw": {
    get: operations["getRawTrailPreviews"];
  };
  "/preview/map": {
    get: operations["getTrailMapping"];
  };
  "/preview/find/name/{name}": {
    get: operations["findByLocationOrTrailNames"];
  };
  "/preview/find/code/{code}": {
    get: operations["findByTrailCode"];
  };
  "/poi": {
    get: operations["get_2"];
  };
  "/poi/{id}": {
    get: operations["get_3"];
  };
  "/poi/type/{type}": {
    get: operations["getByMacro"];
  };
  "/poi/trail/{id}": {
    get: operations["getByTrail"];
  };
  "/poi/name/{name}": {
    get: operations["getByNameOrTags"];
  };
  "/poi/count": {
    get: operations["getCount_2"];
  };
  "/place": {
    get: operations["get_4"];
  };
  "/place/{id}": {
    get: operations["get_5"];
  };
  "/place/name/{name}": {
    get: operations["getLikeNameOrTags"];
  };
  "/media": {
    get: operations["getMedia"];
  };
  "/media/{id}": {
    get: operations["getById_3"];
  };
  "/maintenance/past": {
    get: operations["getPastMaintenance"];
  };
  "/maintenance/past/{id}": {
    get: operations["getPastMaintenanceById"];
  };
  "/maintenance/past/count": {
    get: operations["getCountPast"];
  };
  "/maintenance/future": {
    get: operations["getFutureMaintenance"];
  };
  "/maintenance/future/count": {
    get: operations["getCountFuture"];
  };
  "/maintenance/count": {
    get: operations["getCount_3"];
  };
  "/instance": {
    get: operations["get_6"];
  };
  "/geo-tool/polyline_altitude": {
    get: operations["getAltitudeTrail"];
  };
  "/geo-tool/altitude": {
    get: operations["geoLocateTrail_2"];
  };
  "/ert/localities": {
    get: operations["get_7"];
  };
  "/dataset": {
    get: operations["getTrailDatasetV"];
  };
  "/announcement": {
    get: operations["get_8"];
  };
  "/announcement/{id}": {
    get: operations["get_9"];
  };
  "/admin/diagnose/weather": {
    get: operations["testWeather"];
  };
  "/admin/diagnose/altitude": {
    get: operations["testAltitude"];
  };
  "/accessibility/{id}": {
    get: operations["getById_4"];
  };
  "/accessibility/unresolved": {
    get: operations["getNotSolved"];
  };
  "/accessibility/unresolved/{trailId}": {
    get: operations["getNotSolvedByTrailId"];
  };
  "/accessibility/solved": {
    get: operations["getSolved"];
  };
  "/accessibility/solved/{trailId}": {
    get: operations["getSolvedByTrailId"];
  };
  "/accessibility/count": {
    get: operations["getCount_4"];
  };
  "/admin/trail/{id}": {
    delete: operations["deleteById"];
  };
  "/admin/report/{id}": {
    delete: operations["deleteAccessibilityNotificationReport"];
  };
  "/admin/raw/{id}": {
    delete: operations["deleteById_1"];
  };
  "/admin/poi/{id}": {
    delete: operations["deletePoi"];
  };
  "/admin/place/{id}": {
    delete: operations["delete"];
  };
  "/admin/media/{id}": {
    delete: operations["deleteById_2"];
  };
  "/admin/maintenance/{id}": {
    delete: operations["deleteMaintenance"];
  };
  "/admin/announcement/{id}": {
    delete: operations["delete_1"];
  };
  "/admin/accessibility/{id}": {
    delete: operations["deleteAccessibilityNotification"];
  };
}

export interface components {
  schemas: {
    AccessibilityReportDto: {
      id?: string;
      description?: string;
      trailId?: string;
      email?: string;
      telephone?: string;
      issueId?: string;
      reportDate?: string;
      valid?: boolean;
      coordinates?: components["schemas"]["CoordinatesDto"];
      recordDetails?: components["schemas"]["RecordDetailsDto"];
    };
    AccessibilityReportResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["AccessibilityReportDto"][];
    };
    CoordinatesDto: {
      longitude?: number;
      latitude?: number;
      altitude?: number;
    };
    RecordDetailsDto: {
      uploadedOn?: string;
      uploadedBy?: string;
      onInstance?: string;
      realm?: string;
    };
    CycloDetailsDto: {
      cycloClassification?:
        | "TC"
        | "TC_PLUS"
        | "MC"
        | "MC_PLUS"
        | "BC"
        | "BC_PLUS"
        | "OC"
        | "OC_PLUS"
        | "EC"
        | "NO"
        | "UNCLASSIFIED";
      officialEta?: number;
      wayForward?: components["schemas"]["CycloFeasibilityDto"];
      wayBack?: components["schemas"]["CycloFeasibilityDto"];
      description?: string;
    };
    CycloFeasibilityDto: {
      feasible?: boolean;
      portage?: number;
    };
    FileDetailsDto: {
      uploadedOn?: string;
      uploadedBy?: string;
      onInstance?: string;
      realm?: string;
      filename?: string;
      originalFilename?: string;
      lastModifiedBy?: string;
    };
    KeyValueDto: {
      key?: string;
      value?: string;
    };
    LinkedMediaDto: {
      id?: string;
      description?: string;
      keyVal?: components["schemas"]["KeyValueDto"][];
    };
    PlaceRefDto: {
      name?: string;
      coordinates?: components["schemas"]["CoordinatesDto"];
      placeId?: string;
      encounteredTrailIds?: string[];
      dynamicCrossway?: boolean;
    };
    StaticTrailDetailsDto: {
      pathGpx?: string;
      pathKml?: string;
      pathPdf?: string;
    };
    StatsTrailMetadataDto: {
      totalRise?: number;
      totalFall?: number;
      eta?: number;
      length?: number;
      highestPlace?: number;
      lowestPlace?: number;
    };
    TrailCoordinatesDto: {
      distanceFromTrailStart?: number;
      latitude?: number;
      longitude?: number;
      altitude?: number;
    };
    TrailDto: {
      id?: string;
      code?: string;
      name?: string;
      description?: string;
      variant?: boolean;
      officialEta?: number;
      startLocation?: components["schemas"]["PlaceRefDto"];
      endLocation?: components["schemas"]["PlaceRefDto"];
      locations?: components["schemas"]["PlaceRefDto"][];
      classification?: "T" | "E" | "EE" | "EEA" | "UNCLASSIFIED";
      country?: string;
      statsTrailMetadata?: components["schemas"]["StatsTrailMetadataDto"];
      coordinates?: components["schemas"]["TrailCoordinatesDto"][];
      mediaList?: components["schemas"]["LinkedMediaDto"][];
      lastUpdate?: string;
      territorialDivision?: string;
      maintainingSection?: string;
      status?: "DRAFT" | "PUBLIC";
      fileDetails?: components["schemas"]["FileDetailsDto"];
      staticTrailDetails?: components["schemas"]["StaticTrailDetailsDto"];
      cycloDetails?: components["schemas"]["CycloDetailsDto"];
    };
    TrailResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["TrailDto"][];
    };
    TrailImportDto: {
      code?: string;
      name?: string;
      description?: string;
      officialEta?: number;
      startLocation?: components["schemas"]["PlaceRefDto"];
      endLocation?: components["schemas"]["PlaceRefDto"];
      locations?: components["schemas"]["PlaceRefDto"][];
      crossways?: components["schemas"]["PlaceRefDto"][];
      classification?: "T" | "E" | "EE" | "EEA" | "UNCLASSIFIED";
      country?: string;
      coordinates?: components["schemas"]["TrailCoordinatesDto"][];
      maintainingSection?: string;
      territorialDivision?: string;
      linkedMediaDtos?: components["schemas"]["LinkedMediaDto"][];
      lastUpdate?: string;
      fileDetailsDto?: components["schemas"]["FileDetailsDto"];
      trailStatus?: "DRAFT" | "PUBLIC";
      variant?: boolean;
    };
    PoiDto: {
      id?: string;
      name?: string;
      description?: string;
      tags?: string[];
      macroType?: "BELVEDERE" | "SUPPORT" | "CULTURAL" | "CURIOSITY";
      microType?: string[];
      mediaList?: components["schemas"]["LinkedMediaDto"][];
      trailIds?: string[];
      coordinates?: components["schemas"]["CoordinatesDto"];
      externalResources?: string[];
      keyVal?: components["schemas"]["KeyValueDto"][];
      recordDetails?: components["schemas"]["RecordDetailsDto"];
    };
    PoiResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["PoiDto"][];
    };
    PlaceDto: {
      id?: string;
      name?: string;
      description?: string;
      tags?: string[];
      mediaIds?: string[];
      coordinates?: components["schemas"]["CoordinatesDto"][];
      crossingTrailIds?: string[];
      recordDetails?: components["schemas"]["RecordDetailsDto"];
      dynamic?: boolean;
    };
    PlaceResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["PlaceDto"][];
    };
    LinkedPlaceDto: {
      trailId?: string;
      placeId?: string;
      coordinatesDto?: components["schemas"]["CoordinatesDto"];
    };
    MaintenanceDto: {
      id?: string;
      date?: string;
      trailId?: string;
      meetingPlace?: string;
      description?: string;
      contact?: string;
      recordDetails?: components["schemas"]["RecordDetailsDto"];
    };
    MaintenanceResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["MaintenanceDto"][];
    };
    AnnouncementDto: {
      id?: string;
      name?: string;
      description?: string;
      relatedTopic?: components["schemas"]["AnnouncementRelatedTopicDto"];
      type?: "EVENT" | "INFO" | "WARNING" | "EMERGENCY";
      valid?: boolean;
      recordDetails?: components["schemas"]["RecordDetails"];
    };
    AnnouncementRelatedTopicDto: {
      announcementTopicType?:
        | "TRAIL"
        | "POI"
        | "PLACE"
        | "ACCESSIBILITY_NOTIFICATION"
        | "MAINTENANCE";
      id?: string;
    };
    RecordDetails: {
      uploadedOn?: string;
      uploadedBy?: string;
      onInstance?: string;
      realm?: string;
    };
    AnnouncementResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["AnnouncementDto"][];
    };
    AccessibilityNotificationDto: {
      id?: string;
      description?: string;
      trailId?: string;
      reportDate?: string;
      resolutionDate?: string;
      minor?: boolean;
      resolution?: string;
      coordinates?: components["schemas"]["CoordinatesDto"];
      recordDetails?: components["schemas"]["RecordDetailsDto"];
    };
    AccessibilityResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["AccessibilityNotificationDto"][];
    };
    PointGeolocationDto: {
      coordinatesDto?: components["schemas"]["CoordinatesDto"];
      distance?: number;
    };
    Coordinates2D: {
      latitude?: number;
      longitude?: number;
    };
    LocateDto: {
      rectangleDto?: components["schemas"]["RectangleDto"];
      trailIdsNotToLoad?: string[];
    };
    RectangleDto: {
      bottomLeft?: components["schemas"]["Coordinates2D"];
      topRight?: components["schemas"]["Coordinates2D"];
    };
    TrailMappingDto: {
      id?: string;
      code?: string;
      name?: string;
    };
    TrailMappingResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["TrailMappingDto"][];
    };
    GeoLineDto: {
      coordinates?: components["schemas"]["Coordinates2D"][];
    };
    TrailIntersectionDto: {
      points?: components["schemas"]["CoordinatesDto"][];
      trail?: components["schemas"]["TrailDto"];
    };
    TrailIntersectionResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["TrailIntersectionDto"][];
    };
    ResourceGeneratorResponse: {
      status?: "OK" | "BUSY";
    };
    GenerateRequestDto: {
      ids?: string[];
    };
    UnLinkeMediaRequestDto: {
      id?: string;
    };
    MediaDto: {
      creationDate?: string;
      id?: string;
      name?: string;
      fileName?: string;
      extension?: string;
      fileUrl?: string;
      resolutionSuffixes?: string[];
      mime?: string;
      fileSize?: number;
      fileDetails?: components["schemas"]["FileDetailsDto"];
    };
    MediaResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["MediaDto"][];
    };
    TrailRawDto: {
      id?: string;
      name?: string;
      description?: string;
      startPos?: components["schemas"]["TrailCoordinatesDto"];
      finalPos?: components["schemas"]["TrailCoordinatesDto"];
      coordinates?: components["schemas"]["TrailCoordinatesDto"][];
      fileDetails?: components["schemas"]["FileDetailsDto"];
    };
    TrailRawResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["TrailRawDto"][];
    };
    AccessibilityNotificationResolutionDto: {
      id?: string;
      resolution?: string;
      resolutionDate?: string;
    };
    CountDto: {
      count?: number;
    };
    CountResponse: {
      status?: "OK" | "ERROR";
      message?: string[];
      content?: components["schemas"]["CountDto"];
    };
    TrailPreviewDto: {
      id?: string;
      code?: string;
      classification?: "T" | "E" | "EE" | "EEA" | "UNCLASSIFIED";
      startPos?: components["schemas"]["PlaceRefDto"];
      finalPos?: components["schemas"]["PlaceRefDto"];
      locations?: components["schemas"]["PlaceRefDto"][];
      bikeData?: boolean;
      trailStatus?: "DRAFT" | "PUBLIC";
      statsTrailMetadata?: components["schemas"]["StatsTrailMetadataDto"];
      fileDetails?: components["schemas"]["FileDetailsDto"];
    };
    TrailPreviewResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["TrailPreviewDto"][];
    };
    InstanceInfoDto: {
      realm?: string;
      instance?: string;
      runningVersion?: string;
    };
    Coordinates2DDto: {
      longitude?: number;
      latitude?: number;
    };
    CityRefDto: {
      istat?: string;
      city?: string;
      province?: string;
      province_short?: string;
      iat?: components["schemas"]["IatDto"][];
    };
    ContactDto: {
      label?: string;
      type?: string;
      value?: string;
    };
    IatDto: {
      name?: string;
      address?: string;
      number?: string;
      coordinates?: components["schemas"]["CoordinatesDto"];
      contacts?: components["schemas"]["ContactDto"][];
    };
    ImageDto: {
      url?: string;
      thumb?: string;
      title?: string;
      name?: string;
      width?: number;
      height?: number;
      license?: string;
      licenseUrl?: string;
    };
    LocalityDto: {
      id?: string;
      name?: string;
      description?: string;
      coordinates?: components["schemas"]["CoordinatesDto"][];
      image?: components["schemas"]["ImageDto"][];
      relatingCity?: components["schemas"]["CityRefDto"];
      recordDetails?: components["schemas"]["RecordDetailsDto"];
      importedOn?: string;
    };
    LocalityResponse: {
      currentPage?: number;
      totalPages?: number;
      size?: number;
      totalCount?: number;
      status?: "OK" | "ERROR";
      messages?: string[];
      content?: components["schemas"]["LocalityDto"][];
    };
    TrailDatasetVersion: {
      version?: number;
      lastUpdate?: string;
    };
    DiagnoseResponse: {
      service?: string;
      success?: boolean;
      time?: string;
    };
  };
}

export interface operations {
  validate: {
    parameters: {
      path: {
        validationId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  updateTrail: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrailDto"];
      };
    };
  };
  importTrail: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrailImportDto"];
      };
    };
  };
  update: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccessibilityReportResponse"];
          "application/xml": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessibilityReportDto"];
        "application/xml": components["schemas"]["AccessibilityReportDto"];
      };
    };
  };
  create_5: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccessibilityReportResponse"];
          "application/xml": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessibilityReportDto"];
        "application/xml": components["schemas"]["AccessibilityReportDto"];
      };
    };
  };
  upgradeReport: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  update_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PoiDto"];
      };
    };
  };
  create_6: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PoiDto"];
      };
    };
  };
  create: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceDto"];
      };
    };
  };
  update_2: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceDto"];
      };
    };
  };
  unLinkTrailToPlace: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkedPlaceDto"];
      };
    };
  };
  addMedia: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkedMediaDto"];
      };
    };
  };
  deleteMedia: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnLinkeMediaRequestDto"];
      };
    };
  };
  linkTrailToPlace: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkedPlaceDto"];
      };
    };
  };
  create_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MaintenanceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceDto"];
      };
    };
  };
  create_2: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AnnouncementResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnnouncementDto"];
      };
    };
  };
  update_3: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AnnouncementResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnnouncementDto"];
      };
    };
  };
  create_3: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccessibilityResponse"];
          "application/xml": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessibilityNotificationDto"];
        "application/xml": components["schemas"]["AccessibilityNotificationDto"];
      };
    };
  };
  create_4: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccessibilityReportResponse"];
          "application/xml": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessibilityReportDto"];
        "application/xml": components["schemas"]["AccessibilityReportDto"];
      };
    };
  };
  geolocatePlace: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PointGeolocationDto"];
      };
    };
  };
  geoLocateTrail: {
    parameters: {
      query: {
        level?: "LOW" | "MEDIUM" | "HIGH" | "FULL";
        isDraftTrailVisible?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocateDto"];
      };
    };
  };
  geoLocateTrail_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailMappingResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RectangleDto"];
      };
    };
  };
  findTrailIntersection: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailIntersectionResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeoLineDto"];
      };
    };
  };
  radialDistance: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": number;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CoordinatesDto"][];
      };
    };
  };
  updateTrailStatus: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrailDto"];
      };
    };
  };
  addPlaceToTrail: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceRefDto"];
      };
    };
  };
  removePlaceFromTrail: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceRefDto"];
      };
    };
  };
  addMediaToTrail: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkedMediaDto"];
      };
    };
  };
  removeMediaFromTrail: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnLinkeMediaRequestDto"];
      };
    };
  };
  downloadCsv: {
    parameters: {
      query: {
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "text/plain": string[];
        };
      };
    };
  };
  getGenerationResourceStatus: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ResourceGeneratorResponse"];
        };
      };
    };
  };
  generateResource: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ResourceGeneratorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["GenerateRequestDto"];
      };
    };
  };
  generateResource_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["ResourceGeneratorResponse"];
        };
      };
    };
  };
  addMediaToPoi: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkedMediaDto"];
      };
    };
  };
  removeMediaFromPoi: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnLinkeMediaRequestDto"];
      };
    };
  };
  upload: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MediaResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          file?: string;
        };
      };
    };
  };
  importGpx: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["TrailRawResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          file?: string;
        };
      };
    };
  };
  checkMatchingTrails: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailMappingResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrailRawDto"];
      };
    };
  };
  importMassiveGpx: {
    parameters: {
      query: {
        files: string[];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["TrailRawResponse"];
        };
      };
    };
  };
  resolveNotification: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessibilityNotificationResolutionDto"];
      };
    };
  };
  get: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
        level?: "LOW" | "MEDIUM" | "HIGH" | "FULL";
        isDraftTrailVisible?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
  };
  getById: {
    parameters: {
      path: {
        id: string;
      };
      query: {
        level?: "LOW" | "MEDIUM" | "HIGH" | "FULL";
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
  };
  getByPlaceId: {
    parameters: {
      path: {
        id: string;
      };
      query: {
        level?: string;
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
  };
  getCount: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  getById_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  getUpgraded: {
    parameters: {
      path: {
        realm: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  getByTrailId: {
    parameters: {
      path: {
        id: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  getUnapgraded: {
    parameters: {
      path: {
        realm: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  getCount_1: {
    parameters: {
      path: {
        realm: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  get_1: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailRawResponse"];
        };
      };
    };
  };
  getById_2: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailRawResponse"];
        };
      };
    };
  };
  getTrailPreviews: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
        isDraftTrailVisible?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailPreviewResponse"];
        };
      };
    };
  };
  getPreviewById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailPreviewResponse"];
        };
      };
    };
  };
  getRawTrailPreviews: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailPreviewResponse"];
        };
      };
    };
  };
  getTrailMapping: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
        isDraftTrailVisible?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailMappingResponse"];
        };
      };
    };
  };
  findByLocationOrTrailNames: {
    parameters: {
      path: {
        name: string;
      };
      query: {
        realm?: string;
        skip?: number;
        limit?: number;
        isDraftTrailVisible?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailPreviewResponse"];
        };
      };
    };
  };
  findByTrailCode: {
    parameters: {
      path: {
        code: string;
      };
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
        isDraftTrailVisible?: boolean;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailPreviewResponse"];
        };
      };
    };
  };
  get_2: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
  };
  get_3: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
  };
  getByMacro: {
    parameters: {
      path: {
        type: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
  };
  getByTrail: {
    parameters: {
      path: {
        id: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
  };
  getByNameOrTags: {
    parameters: {
      path: {
        name: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
  };
  getCount_2: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  get_4: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        isDynamicShowing?: boolean;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
  };
  get_5: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
  };
  getLikeNameOrTags: {
    parameters: {
      path: {
        name: string;
      };
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
  };
  getMedia: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MediaResponse"];
        };
      };
    };
  };
  getById_3: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MediaResponse"];
        };
      };
    };
  };
  getPastMaintenance: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MaintenanceResponse"];
        };
      };
    };
  };
  getPastMaintenanceById: {
    parameters: {
      path: {
        id: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MaintenanceResponse"];
        };
      };
    };
  };
  getCountPast: {
    parameters: {
      query: {
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  getFutureMaintenance: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MaintenanceResponse"];
        };
      };
    };
  };
  getCountFuture: {
    parameters: {
      query: {
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  getCount_3: {
    parameters: {
      query: {
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  get_6: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["InstanceInfoDto"];
        };
      };
    };
  };
  getAltitudeTrail: {
    parameters: {
      query: {
        coordinatesDtoList: components["schemas"]["Coordinates2DDto"][];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CoordinatesDto"][];
        };
      };
    };
  };
  geoLocateTrail_2: {
    parameters: {
      query: {
        latitude: number;
        longitude: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CoordinatesDto"];
        };
      };
    };
  };
  get_7: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        latitude: number;
        longitude: number;
        distance: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["LocalityResponse"];
        };
      };
    };
  };
  getTrailDatasetV: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailDatasetVersion"];
        };
      };
    };
  };
  get_8: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AnnouncementResponse"];
        };
      };
    };
  };
  get_9: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AnnouncementResponse"];
        };
      };
    };
  };
  testWeather: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DiagnoseResponse"];
        };
      };
    };
  };
  testAltitude: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DiagnoseResponse"];
        };
      };
    };
  };
  getById_4: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
  };
  getNotSolved: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
  };
  getNotSolvedByTrailId: {
    parameters: {
      path: {
        trailId: string;
      };
      query: {
        skip?: number;
        limit?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
  };
  getSolved: {
    parameters: {
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
  };
  getSolvedByTrailId: {
    parameters: {
      path: {
        trailId: string;
      };
      query: {
        skip?: number;
        limit?: number;
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
  };
  getCount_4: {
    parameters: {
      query: {
        realm?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CountResponse"];
        };
      };
    };
  };
  deleteById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailResponse"];
        };
      };
    };
  };
  deleteAccessibilityNotificationReport: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityReportResponse"];
        };
      };
    };
  };
  deleteById_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TrailRawResponse"];
        };
      };
    };
  };
  deletePoi: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PoiResponse"];
        };
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["PlaceResponse"];
        };
      };
    };
  };
  deleteById_2: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MediaResponse"];
        };
      };
    };
  };
  deleteMaintenance: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["MaintenanceResponse"];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: unknown;
    };
  };
  deleteAccessibilityNotification: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessibilityResponse"];
        };
      };
    };
  };
}
